import type { Metadata } from "next";
import "./globals.css";
import Navibar from "@/components/nav/Navibar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover"
        />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
      </head>
      <body>
        <div className="h-full">
          <div className="w-full min-w-[320px] max-w-[600px] mx-auto my-0  min-h-full">
            {children}
            <Navibar />
          </div>
        </div>
      </body>
    </html>
  );
}
