import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
      </head>
      <body>
        <div className="h-full m-0 p-0">
          <div className="w-full min-w-[320px] max-w-[600px] mx-auto my-0  min-h-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
